// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uymovafdypbyuogilmki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bW92YWZkeXBieXVvZ2lsbWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzM1MDMsImV4cCI6MjA1NTY0OTUwM30.VvOYglSHvX_DKpQI5ToIFFiZ6J_rtIzm-8AWQEQptcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);